language: scala
jdk:
- openjdk11
dist: bionic
before_install:
- bash scripts/decrypt_files_if_not_pr.sh
install:
  - |
    # update this only when sbt-the-bash-script needs to be updated
    export SBT_LAUNCHER=1.4.8
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.coursier/cache -name "*.lock" -type f -delete
cache:
  directories:
  - "$HOME/.sbt/1.0"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/cache"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
script:
- sbt test
deploy:
- provider: script
  script: sbt publishRelease
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+).*?"
